### ISSUE TITLE
Different Naming

### ISSUE THREAD

**Issue by jakobsuckow** [RobinBlomberg/kysely-codegen#211]
Hey there, 

big fan of this library. Wondering if there is a way of adding a suffix to each Column ? I.e. suffix "Model" would result in 

```import { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CompanyModel {
  id: Generated<number>;
  name: string;
}

export interface UserModel {
  company_id: number | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  is_active: boolean;
  name: string;
  updated_at: Timestamp;
}

export interface DB {
  company: CompanyModel;
  user: UserModel;
}

```

Much appreciated

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/211">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/211/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/211/pledge.svg">
</picture>
</a>

**Comment by vrachev** [comment]
Was looking for this myself as well. A workaround is to `import User as UserModel` in a different file and export UserModel for wider consumption. 

Some sort of column naming option would be great though. 

@RobinBlomberg have you started working on this (asking bc you've added the 'in-progress' label)? If not I may have some time to take a stab

**Comment by RobinBlomberg** [comment]
Hello @vrachev. I'm currently working on a branch that adds:
- Configuration file support
- Improved support for custom singularization rules, which adds a way to e.g. add the suffix `Model` to all table names (slightly hacky, but it works)
- Custom serializer support, which makes it possible to extend the serializer in a more fine-grained manner and have full control of how e.g. table names are serialized

I haven't had the chance to finalize this yet, but it's working well so far.

**Comment by vrachev** [comment]
Awesome! No rush. Appreciate the great work.

**Comment by noudadrichem** [comment]
I'm also looking for Prefix or Postfixes on generated types. Love the library, tyvm!

**Comment by sarahhenkens** [comment]
@RobinBlomberg I tried using your approach with a custom serializer but I run into this runtime error:

```
sarah@remote-dev:~/followmytv/api$ yarn run kysely-codegen
yarn run v1.22.22
$ /home/sarah/followmytv/api/node_modules/.bin/kysely-codegen
• Loaded environment variables from '.kysely-codegenrc.env'.
• Using dialect 'mysql'.
• Introspecting database...
/home/sarah/followmytv/api/node_modules/kysely-codegen/dist/generator/generator/serializer.js:114
        data += this.serializeStatements((0, transformer_1.transform)({
                     ^

TypeError: this.serializeStatements is not a function
    at Object.serializeFile (/home/sarah/followmytv/api/node_modules/kysely-codegen/dist/generator/generator/serializer.js:114:22)
    at Object.serializeFile (/home/sarah/followmytv/api/node_modules/kysely-codegen/node_modules/zod/lib/types.js:3011:40)
    at serializeFromMetadata (/home/sarah/followmytv/api/node_modules/kysely-codegen/dist/generator/generator/generate.js:75:23)
    at generate (/home/sarah/followmytv/api/node_modules/kysely-codegen/dist/generator/generator/generate.js:19:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Cli.generate (/home/sarah/followmytv/api/node_modules/kysely-codegen/dist/cli/cli.js:64:24)
    at async Cli.run (/home/sarah/followmytv/api/node_modules/kysely-codegen/dist/cli/cli.js:181:16)

Node.js v22.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is my config:
```ts
import { TypeScriptSerializer, InterfaceDeclarationNode } from 'kysely-codegen';
import { Config } from 'kysely-codegen/dist/cli/config';

class CustomTypeScriptSerializer extends TypeScriptSerializer {
  override serializeInterfaceDeclaration(node: InterfaceDeclarationNode) {
    let data = '';
    data += 'interface ';
    data += this.serializeIdentifier(node.id);

    if (node.id.name !== 'DB') {
      data += 'Table';
    }

    data += ' ';
    data += this.serializeObjectExpression(node.body);
    return data;
  }
}

const config: Config = {
  serializer: new CustomTypeScriptSerializer(),
  dialect: 'mysql',
  envFile: '.kysely-codegenrc.env',
  outFile: './kysely/db.d.ts',
  camelCase: true,
  singularize: true,
};

export default config;

```

**Comment by Andrew-Chen-Wang** [comment]
@sarahhenkens this should help https://github.com/RobinBlomberg/kysely-codegen/issues/229#issuecomment-2762149908
