### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by harastaivan** [RobinBlomberg/kysely-codegen#83]
Hello,
I tried to use `kysely-codegen` with Deno. Since `kysely` supports Deno, I thought `kysely-codegen` will work too.

I ran:

```sh
deno run npm:kysely-codegen
```

It outputs:

```text
• Loaded environment variables from .env file.
• No dialect specified. Assuming 'postgres'.
```

But it seems it doesn't do anything. Could you test it and possibly help me what's the problem? I'm happy to help with investigation but need some guide

**Comment by kbaba1001** [comment]
I was able to run like this on `deno.json`: 

```
"tasks": {
	"kysely-codegen": "echo \"import 'npm:pg@^8.11.3'; import 'npm:kysely-codegen@^0.11.0';\" | deno run --allow-env -A npm:kysely-codegen@^0.11.0 - kysely-codegen --dialect=postgres --out-file ./src/database-types.ts --env-file .env"
},
```

**Comment by w7it** [comment]
Or try to cache required package before run codegen:
```sh
deno cache npm:pg && deno run -A npm:kysely-codegen --out-file=./db_schema.ts 
```

**Comment by harrysolovay** [comment]
I get the following error:

```
npm error code ENOENT
npm error syscall open
npm error path /Users/harrysolovay/Dev/crosshatch/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/harrysolovay/Dev/crosshatch/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /Users/harrysolovay/.npm/_logs/2024-11-10T16_27_37_858Z-debug-0.log
```

<details>
  <summary>Complete log</summary>

```
0 verbose cli /opt/homebrew/Cellar/node/23.1.0_1/bin/node /opt/homebrew/bin/npm
1 info using npm@10.9.0
2 info using node@v23.1.0
3 silly config load:file:/opt/homebrew/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/harrysolovay/Dev/crosshatch/.npmrc
5 silly config load:file:/Users/harrysolovay/.npmrc
6 silly config load:file:/opt/homebrew/etc/npmrc
7 verbose title npm run npm:kysely-codegen postgres client/schema.ts
8 verbose argv "run" "-A" "npm:kysely-codegen" "--dialect" "postgres" "--out-file" "client/schema.ts"
9 verbose logfile logs-max:10 dir:/Users/harrysolovay/.npm/_logs/2024-11-10T16_27_37_858Z-
10 verbose logfile /Users/harrysolovay/.npm/_logs/2024-11-10T16_27_37_858Z-debug-0.log
11 silly logfile done cleaning log files
12 verbose stack Error: Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/harrysolovay/Dev/crosshatch/package.json'
12 verbose stack     at async open (node:internal/fs/promises:639:25)
12 verbose stack     at async readFile (node:internal/fs/promises:1239:14)
12 verbose stack     at async read (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/package-json/lib/read-package.js:9:18)
12 verbose stack     at async PackageJson.load (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/package-json/lib/index.js:130:31)
12 verbose stack     at async PackageJson.normalize (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/package-json/lib/index.js:116:5)
12 verbose stack     at async #run (/opt/homebrew/lib/node_modules/npm/lib/commands/run-script.js:86:13)
12 verbose stack     at async RunScript.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/run-script.js:40:7)
12 verbose stack     at async Npm.exec (/opt/homebrew/lib/node_modules/npm/lib/npm.js:207:9)
12 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli/entry.js:74:5)
13 error code ENOENT
14 error syscall open
15 error path /Users/harrysolovay/Dev/crosshatch/package.json
16 error errno -2
17 error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/harrysolovay/Dev/crosshatch/package.json'
18 error enoent This is related to npm not being able to find a file.
18 error enoent
19 verbose cwd /Users/harrysolovay/Dev/crosshatch
20 verbose os Darwin 24.1.0
21 verbose node v23.1.0
22 verbose npm  v10.9.0
23 verbose exit -2
24 verbose code -2
25 error A complete log of this run can be found in: /Users/harrysolovay/.npm/_logs/2024-11-10T16_27_37_858Z-debug-0.log
```

</details>

Any advice?

**Comment by maheshbansod** [comment]
I get an error `write EBADF` and the program quits.

**Comment by harrysolovay** [comment]
I works fine for me as long as I enable the `node_modules` dir:

`deno.json`

```diff
 {
+  "nodeModulesDir": "auto",
   "tasks": {
     deno run -A npm:kysely-codegen --dialect postgres --out-file schema.ts
   }
 }
```
